# Generated by Django 5.1 on 2024-09-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('core', '0008_userprofile_gender_alter_userprofile_followers_and_more'),
    ]

    operations = [
    ]
