# Generated by Django 5.1 on 2024-09-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20240904_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=30)),
                ('siteUrl', models.CharField(max_length=500)),
                ('urlNoProtocol', models.CharField(max_length=450)),
                ('siteType', models.CharField(max_length=30)),
            ],
        ),
    ]
