# Generated by Django 5.0.5 on 2024-09-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_learningsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.SlugField(default='Something...'),
        ),
    ]
