# Generated by Django 5.0.5 on 2024-09-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_userprofile_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='url',
            new_name='user_url',
        ),
    ]
