# Generated by Django 5.1 on 2024-09-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='pid',
            new_name='uniqueID',
        ),
    ]
