# Generated by Django 5.0.5 on 2024-09-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_reportedmessage_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedmessage',
            name='messageText',
            field=models.TextField(default='BLANK MESSAGE'),
        ),
    ]
