# Generated by Django 5.0.5 on 2024-09-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_reportedmessage_messagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedmessage',
            name='messageText',
            field=models.TextField(),
        ),
    ]
